### ISSUE TITLE
Error once the page has been cached.

### ISSUE THREAD

**Issue by sangeethj** [mpchadwick/Mpchadwick_PageCacheHitRate#38]
Hi,

On enabling the module, I am getting error has below. Magento version  1.12.0.2 and we have Redis for both the default cache ( default array) and the full page cache. Appreciate your help in the regard.

a:4:{i:0;s:46:"Mage registry key "_helper/log" already exists";i:1;s:1203:"#0 /var/www/web/app/Mage.php(222): Mage::throwException('Mage registry k...')
#1 /var/www//web/app/Mage.php(546): Mage::register('_helper/log', Object(Mage_Log_Helper_Data))
#2 /var/www/web/app/Mage.php(810): Mage::helper('log')
#3 /var/www/web/app/code/community/Mpchadwick/PageCacheHitRate/Model/Tracker/File.php(12): Mage::log('{"url":"http:\\/...', NULL, 'mpchadwick_page...', true)
#4 /var/www/web/app/code/community/Mpchadwick/PageCacheHitRate/Model/Tracker/Abstract.php(27): Mpchadwick_PageCacheHitRate_Model_Tracker_File->_track('RequestResponse', Array, 'file')
#5 /var/www/web/app/code/community/Mpchadwick/PageCacheHitRate/Model/Processor.php(43): Mpchadwick_PageCacheHitRate_Model_Tracker_Abstract->track('RequestResponse', Array, 'file')
#6 /var/www/web/app/code/community/Mage/Core/Model/Cache.php(626): Mpchadwick_PageCacheHitRate_Model_Processor->extractContent('...')
#7 /var/www/web/app/code/core/Mage/Core/Model/App.php(340): Mage_Core_Model_Cache->processRequest()
#8 /var/www/web/app/Mage.php(683): Mage_Core_Model_App->run(Array)

Thanks

**Comment by mpchadwick** [comment]
Hey @sangeethj - Do you have SUPEE-10415 applied? I was just doing some testing and noticed that the `file` tracker will no longer work due to the issue described [here](https://maxchadwick.xyz/blog/supee-10415-causing-every-page-to-404). In the environment I tested in (clean Magento 1.14.3.7 install) it causes a 404 error, but not sure if your environment with 1.12.0.2 might manifest as the backtrace above...
